export { default as Tab } from './tab/tab'
export { default as Share } from './share/share'
export { default as Video } from './video/video'
export { default as Footer } from "./footer/footer";
export { default as Infomation } from './infomation/infomation'
export { default as Evaluation } from './evaluation/evaluation'
export { default as MovieSearch } from './movieSearch/MovieSearch'
export { default as SuggestMovie } from './suggestMovie/suggestMovie'
export { default as TransferList } from './transferList/transferList'
export { default as HeaderMobile } from './header/headerMobile'
export { default as HeaderDesktop } from './header/headerDekstop'
export { default as ContentWithRS } from './renderData/ContentWithRS'
export { default as ContentWithGrid } from './renderData/ContentWithGrid'
export { default as ContentWithRIDS } from './renderData/ContentWithRIDS'
export { default as MovieRatingsBroad } from './MovieRatingsBroad/MovieRatingsBroad'
export {default as MovieCard} from './movieCard/movieCard'